### ISSUE TITLE
Work with CSS Modules

### ISSUE THREAD

**Issue by itayganor** [gem-mine/webpack-css-themes-plugin#2]
Hi there :) 

Is there any way to configure this plugin to work with CSS Modules enabled?

(I'm using less, if it matters)

Thanks!

**Comment by githoniel** [comment]
it should work

**Comment by itayganor** [comment]
I made a minimal example by striping down everything unrelated from my project:
https://github.com/itayganor/webpack-css-themes-plugin-reproduction

I receive the following error:

```
(node:16580) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'light' of undefined
```

**Comment by itayganor** [comment]
By the way - how can you switch the themes on runtime?
