### ISSUE TITLE
HMR reports an error in ie11

### ISSUE THREAD

**Issue by ChenGuanglin0924** [gem-mine/webpack-css-themes-plugin#9]
![image](https://user-images.githubusercontent.com/22443356/105002259-eed6ff00-5a6b-11eb-9653-76512df9bf19.png)
![image](https://user-images.githubusercontent.com/22443356/105002290-f8606700-5a6b-11eb-98aa-19130214120c.png)

**Comment by githoniel** [comment]
set `devtool: soucemap`  in webpack， and you will see where report this error

**Comment by githoniel** [comment]
fix in webpack-css-themes-plugin@0.12.2

though I think most people will not run dev-server in IE11
